apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Anvarking/HELM_traning.git'
    targetRevision: HEAD
    path: rabbitmq1
    helm:
      valueFiles:
        - rabbitmq.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true       # Удаляет ресурсы, которых больше нет в Git
      selfHeal: true    # Восстанавливает удалённые или изменённые вручную ресурсы
    syncOptions:
    - CreateNamespace=true
