apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-redis
  namespace: argocd
spec:
  project: prod

  source:
    repoURL: 'git@github.com:Anvarking/HELM_traning.git'
    targetRevision: HEAD
    path: radis
    helm:
      valueFiles:
        - neo-values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true       # Удаляет ресурсы, которых больше нет в Git
      selfHeal: true    # Восстанавливает удалённые или изменённые вручную ресурсы
    syncOptions:
    - CreateNamespace=true
