apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  source:
    path: argo-cd.yaml
    repoURL: https://github.com/Anvarking/HELM_traning.git
    targetRevision: HEAD
  destination:
    namespace: argocd  
    server: https://kubernetes.default.svc
  project: default
